name: Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '{{cookiecutter.python_version}}'
          cache: pip
      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
      - name: Setup pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}
      - name: Check pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Test
        run: pytest --cov=. --cov-branch --cov-report term-missing:skip-covered
        working-directory: ./src/
